Added actions, geo match and IP set
umotif-public/terraform-aws-waf-webaclv2 pull request #18
Opened 2021-03-17 14:32 UTC by lkaastra1

# Description

- Added actions to add blocking or allowing for rules that don't reference a rule group
- Added supported for geo matching
- Added support for IP set references

2021-03-18 09:15 UTC, marcincuber requested changes

2021-03-18 09:15 UTC, marcincuber commented on main.tf
> +        dynamic "ip_set_reference_statement" {
This is already supported under in 
```
dynamic "rule" {
    for_each = var.ip_set_rules
...
```
Why do we need this here?

2021-03-18 09:15 UTC, marcincuber commented on main.tf
> +        dynamic "geo_match_statement" {
This is fine, can we also add this to 
```
dynamic "rule" {
    for_each = var.ip_set_rules
...
```

2021-03-18 09:15 UTC, marcincuber commented on main.tf
> +      dynamic "override_action" {
This is changing the behaviour and forces override_action to be specified whereas previously it was defaulting to `none`. Core example requires updating. We also need to expand that examples to see the usage of `geo_match_statement` and potentially `ip_set_reference_statement`

2021-04-15 15:28 UTC, lkaastra1 commented
Removed the `ip_set_reference_statement` since it is already supported. Also move `geo_match_statement` to its own variable similar to the ip set rules as to not affect functionally of `override_action` for var.rules

2021-04-16 06:50 UTC, marcincuber approved these changes

2021-04-16 08:06 UTC, seanpascual approved these changes
LGTM

2021-04-19 07:31 UTC, merged