DEVOPS-957 Terratests
umotif-public/terraform-aws-waf-webaclv2 pull request #22
Opened 2021-05-28 10:23 UTC by seanpascual

# Description

Please explain the changes you made here and link to any relevant issues.

2021-05-28 10:28 UTC, marcincuber requested changes

2021-05-28 13:41 UTC, seanpascual commented on outputs.tf
> +}
Added

2021-06-03 10:33 UTC, Ohid25 commented on .github/workflows/terraform-checks.yaml
> +          terraform_version: 0.15.4
can be set to 0.15.5 now 😄

2021-06-03 10:33 UTC, Ohid25 commented on .github/workflows/test.yaml
> +        terraform_version: 0.15.4
here too

2021-06-03 10:34 UTC, Ohid25 commented on .github/workflows/test.yaml
> +        terraform_version: 0.15.4
or even set a global variable here that controls the version

2021-06-03 10:34 UTC, Ohid25 commented on .github/workflows/test.yaml
> +        go-version: 1.16.3
probably same with go also

2021-06-03 11:54 UTC, Ohid25 approved these changes

2021-06-03 12:30 UTC, marcincuber approved these changes

2021-06-03 12:54 UTC, merged